export const BILLING_SERVICE = 'BILLING';
export const BOOKING_SERVICE='BOOKING';
export const BUS_MANAGEMENT = 'BUS-MANAGEMENT';
export const ITINERARY_MANAGEMENT = 'ITINERARY-MANAGEMENT';

export const RESERVATION_SYSTEM = 'RESERVATION-SYSTEM'
