export enum Provinces {
  Amazonas = 'Amazonas',
  Ancash = 'Ancash',
  Apurimac = 'Apurimac',
  Arequipa = 'Arequipa',
  Ayacucho = 'Ayacucho',
  Cajamarca = 'Cajamarca',
  Callao = 'Callao',
  Cusco = 'Cusco',
  Huancavelica = 'Huancavelica',
  Huanuco = 'Huanuco',
  Ica = 'Ica',
  Junin = 'Junin',
  La_Libertad = 'La Libertad',
  Lambayeque = 'Lambayeque',
  Lima = 'Lima',
  Loreto = 'Loreto',
  Madre_de_Dios = 'Madre de Dios',
  Moquegua = 'Moquegua',
  Pasco = 'Pasco',
  Piura = 'Piura',
  Puno = 'Puno',
  San_Martin = 'San Martin',
  Tacna = 'Tacna',
  Tumbes = 'Tumbes',
  Ucayali = 'Ucayali',
}
